apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx1
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 6
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: joy132/assesment:v2
        ports:
        - containerPort: 80


